name: mysolat_app
description: "A Muslim prayer times app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  adhan: ^2.0.0+1       # Prayer time calculations
  geolocator: ^9.0.2    # Location services
  flutter_qiblah: ^2.2.0  # Qibla direction
  provider: ^6.0.5      # State management
  intl: ^0.18.1         # Date formatting
  shared_preferences: ^2.2.0  # Local storage
  flutter_local_notifications: ^14.1.0  # Notifications
  google_fonts: ^4.0.4  # Typography
  flutter_svg: ^2.0.10+1  # SVG rendering
  http: ^1.1.0          # HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # To be added later
  # assets:
  #   - assets/images/ 